###
GET http://localhost:8080/tutors

###
GET http://localhost:8080/tutors/1

###
POST http://localhost:8080/tutors
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "hourlyRate": 50.0,
  "availableTimes": ["Monday 10am-12pm", "Wednesday 2pm-4pm"],
  "subjectList": [
    {
      "subjectName": "Mathematics"
    },
    {
      "subjectName": "Physics"
    }
  ]
}

